// Code generated by protoc-gen-go.
// source: taskdev.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	taskdev.proto

It has these top-level messages:
	HeartBeatReq
	HeartBeatRsp
	RegisterReq
	RegisterRsp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// 心跳请求 0x00010001
type HeartBeatReq struct {
	SID              *string `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartBeatReq) Reset()                    { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string            { return proto1.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()               {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HeartBeatReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

// 心跳回应 0x00010002
type HeartBeatRsp struct {
	SID              *string `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartBeatRsp) Reset()                    { *m = HeartBeatRsp{} }
func (m *HeartBeatRsp) String() string            { return proto1.CompactTextString(m) }
func (*HeartBeatRsp) ProtoMessage()               {}
func (*HeartBeatRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HeartBeatRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

// 注册请求 0x00010003
type RegisterReq struct {
	SID              *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	Type             *string  `protobuf:"bytes,2,req,name=Type" json:"Type,omitempty"`
	OS               *string  `protobuf:"bytes,3,req,name=OS" json:"OS,omitempty"`
	Arch             *string  `protobuf:"bytes,4,req,name=Arch" json:"Arch,omitempty"`
	Host             *string  `protobuf:"bytes,5,req,name=Host" json:"Host,omitempty"`
	Adress           []string `protobuf:"bytes,6,rep,name=Adress" json:"Adress,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto1.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *RegisterReq) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *RegisterReq) GetOS() string {
	if m != nil && m.OS != nil {
		return *m.OS
	}
	return ""
}

func (m *RegisterReq) GetArch() string {
	if m != nil && m.Arch != nil {
		return *m.Arch
	}
	return ""
}

func (m *RegisterReq) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *RegisterReq) GetAdress() []string {
	if m != nil {
		return m.Adress
	}
	return nil
}

// 注册回应 0x00010004
type RegisterRsp struct {
	RetCode          *int32  `protobuf:"varint,1,req,name=RetCode" json:"RetCode,omitempty"`
	SID              *string `protobuf:"bytes,2,req,name=SID" json:"SID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterRsp) Reset()                    { *m = RegisterRsp{} }
func (m *RegisterRsp) String() string            { return proto1.CompactTextString(m) }
func (*RegisterRsp) ProtoMessage()               {}
func (*RegisterRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterRsp) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *RegisterRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func init() {
	proto1.RegisterType((*HeartBeatReq)(nil), "proto.HeartBeatReq")
	proto1.RegisterType((*HeartBeatRsp)(nil), "proto.HeartBeatRsp")
	proto1.RegisterType((*RegisterReq)(nil), "proto.RegisterReq")
	proto1.RegisterType((*RegisterRsp)(nil), "proto.RegisterRsp")
}

func init() { proto1.RegisterFile("taskdev.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x49, 0x2c, 0xce,
	0x4e, 0x49, 0x2d, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xd2, 0x5c,
	0x3c, 0x1e, 0xa9, 0x89, 0x45, 0x25, 0x4e, 0xa9, 0x89, 0x25, 0x41, 0xa9, 0x85, 0x42, 0xdc, 0x5c,
	0xcc, 0xc1, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0xa8, 0x92, 0xc5, 0x05, 0xa8, 0x92,
	0x09, 0x5c, 0xdc, 0x41, 0xa9, 0xe9, 0x99, 0xc5, 0x25, 0xa9, 0x45, 0xe8, 0x1a, 0x85, 0x78, 0xb8,
	0x58, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0xc0, 0x3c, 0x2e, 0x2e, 0x26, 0xff, 0x60, 0x09, 0x66,
	0x98, 0x8c, 0x63, 0x51, 0x72, 0x86, 0x04, 0x0b, 0x8c, 0xe7, 0x91, 0x5f, 0x5c, 0x22, 0xc1, 0x0a,
	0xe6, 0xf1, 0x71, 0xb1, 0x39, 0xa6, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0xb0, 0x29, 0x30, 0x03, 0x6d,
	0xd0, 0x46, 0xb2, 0x01, 0x68, 0x3b, 0x3f, 0x17, 0x7b, 0x50, 0x6a, 0x89, 0x73, 0x7e, 0x4a, 0x2a,
	0xd8, 0x16, 0x56, 0x98, 0x95, 0x60, 0x4b, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x69, 0x97,
	0xfc, 0xdf, 0x00, 0x00, 0x00,
}
